[package]
name = "wsa-rpc-bridge"
version = "0.1.0"
description = "WSA RPC Bridge - Display WSA Android app media info on Discord Rich Presence"
authors = ["you"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3" }
tauri-plugin-log = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
adb_client = { version = "2", default-features = false }
cxx = "1.0"
